# Generated by Django 4.2.3 on 2023-08-09 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('Course', models.CharField(choices=[('Python', 'Python'), ('Full Stack Developer', 'Full Stack Developer'), ('Software Testing', 'Software Testing'), ('Digital Marketing', 'Digital Marketing')], default=None, max_length=20, verbose_name='Course')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=10)),
                ('ContactNumber', models.BigIntegerField()),
                ('Course', models.CharField(choices=[('Python', 'Python'), ('Full Stack Developer', 'Full Stack Developer'), ('Software Testing', 'Software Testing'), ('Digital Marketing', 'Digital Marketing')], max_length=20, verbose_name='Course')),
                ('Batch', models.CharField(max_length=10)),
                ('Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trackapp.teacher')),
                ('Username_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarksObtained', models.BigIntegerField()),
                ('OutOf', models.BigIntegerField(default=None)),
                ('Student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trackapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('Username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalNumberOfDays', models.BigIntegerField()),
                ('NoOfDaysPresent', models.BigIntegerField()),
                ('Student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trackapp.student')),
            ],
        ),
    ]
