# Generated by Django 4.2.3 on 2023-08-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=200),
        ),
    ]
